apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: development          
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: konstantinnn/my-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080   
      imagePullSecrets:
       - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: development
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001

